global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-user-service'
    static_configs:
      - targets: ['auth-user-service:9101']
  - job_name: 'grpc-gateway'
    static_configs:
      - targets: ['grpc-gateway:9100']
  - job_name: 'problem-service'
    static_configs:
      - targets: ['problem-service:9102']
