apiVersion: v2
name: codex
description: Umbrella chart for Codex microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common-lib
    version: 1.0.0
    repository: "file://../common-lib"
  - name: common
    version: 1.0.6
    repository: "file://../common"
  - name: auth-user-service
    version: 1.0.1
    repository: "file://../auth-user"
  - name: gateway-service
    version: 1.0.1
    repository: "file://../gateway"
  - name: collab-service
    version: 1.0.2
    repository: "file://../collab"
  - name: problem-service
    version: 1.0.1
    repository: "file://../problem"
  - name: code-manage-service
    version: 1.0.1
    repository: "file://../code-manage"
  - name: code-execution-service
    version: 1.0.3
    repository: "file://../code-execution"