# app-services image tags
auth-user-service:
  image:
    tag: "915de32" 

gateway-service:
  image:
    tag: "3860133" 

problem-service:
  image:
    tag: "e9a56ba" 

code-manage-service:
  image:
    tag: "latest" 

code-execution-service:
  image:
    tag: "latest" 

collab-service:
  image:
    tag: "latest"