# app-services image tags
auth-user-service:
  image:
    tag: "latest" 

gateway-service:
  image:
    tag: "latest" 

problem-service:
  image:
    tag: "latest" 

code-manage-service:
  image:
    tag: "latest" 

code-execution-service:
  image:
    tag: "latest" 

collab-service:
  image:
    tag: "latest"