# app-services image tags
auth-user-service:
  image:
    tag: "7324097" 

gateway-service:
  image:
    tag: "736abd2" 

problem-service:
  image:
    tag: "52052b4" 

code-manage-service:
  image:
    tag: "7b75a7e" 

code-execution-service:
  image:
    tag: "latest" 

collab-service:
  image:
    tag: "latest"