apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-user-service
  namespace: app-services
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth-user-service
  template:
    metadata:
      labels:
        app: auth-user-service
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for Redis to be available on port 6379..."
              while ! nc -z -w 1 redis 6379; do
                echo "Redis not yet ready. Sleeping for 5 seconds..."
                sleep 5
              done
              echo "Redis is ready!"
          env:
            - name: REDIS_HOST
              value: "redis"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: auth-user-service
          image: akashcapro/codex-auth-user-service:0.0.4
          imagePullPolicy: Always
          ports:
          - containerPort: 50051 
          - containerPort: 9101 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: REDIS_URL
              value: "redis://redis:6379" 
            - name: GRPC_AUTH_USER_SERVICE_SERVER_URL
              value: "0.0.0.0:50051"
            - name: JWT_ACCESS_TOKEN_EXPIRY
              value: "1h"
            - name: JWT_REFRESH_TOKEN_EXPIRY
              value: "1d"
            - name: NODEMAILER_EMAIL
              value: "codex.platform.official@gmail.com"
            - name: NODEMAILER_SERVICE
              value: gmail
            - name: AUTH_USER_SERVICE_METRICS_PORT
              value: "9101"
            - name: OTP_EXPIRY_SECONDS
              value: "120"
            - name: PROFILE_CACHE_EXPIRY
              value: "86400"
            - name: BLOCKED_USER_CACHE_EXPIRY
              value: "3600"
            - name: OTEL_SERVICE_NAME
              value: "auth-user-service"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317" 
            - name: DEFAULT_GRPC_TIMEOUT
              value: "15000"
            - name: GRPC_PROBLEM_SERVICE_URL
              value: "problem-service:50052"
          envFrom:
            - secretRef:
                name: app-secrets 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-user-service
  namespace: app-services
spec:
  selector:
    app: auth-user-service
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
  - name: metrics
    protocol: TCP
    port: 9101
    targetPort: 9101
