apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-manage-service
  namespace: app-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-manage-service
  template:
    metadata:
      labels:
        app: code-manage-service
    spec:
      initContainers:
        # 'wait-for-kafka' initContainer is REMOVED (no longer needed)
        - name: wait-for-redis
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for Redis to be available on port 6379..."
              until nc -z -w 1 redis 6379; do
                echo "Redis not yet ready. Sleeping for 5 seconds..."
                sleep 5
              done
              echo "Redis is ready!"
          env:
            - name: REDIS_HOST
              value: "redis"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: code-manage-service
          image: akashcapro/codex-code-manage-service:0.0.4
          imagePullPolicy: Always
          ports:
          -  containerPort: 50053
          - containerPort: 9103
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: CODE_MANAGE_SERVICE_METRICS_PORT
              value: "9103"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: SUBMISSION_DETAILS_CACHE_EXPIRY
              value: "600"
            - name: RUN_CODE_DETAILS_CACHE_EXPIRY
              value: "600"
            - name: PROBLEM_DETAILS_CACHE_EXPIRY
              value: "86400"
            - name: GRPC_CODE_MANAGE_SERVICE_SERVER_URL
              value: "0.0.0.0:50053"
            - name: GRPC_PROBLEM_SERVICE_URL
              value: "problem-service:50052"
            - name: DEFAULT_GRPC_TIMEOUT
              value: "15000"
            - name: KAFKA_IDEMPOTENCY_KEY_EXPIRY
              value: "600"
            - name: KAFKA_CODE_MANAGE_SERVICE_CLIENT_ID
              value: 'code-manage-service'
            - name: KAFKA_BROKERS
              value: 'kafka:9092'
            - name: KAFKA_CODE_MANAGE_SERVICE_GROUP_ID
              value: 'code-manage-group'
            - name: KAFKA_MAX_RETRIES
              value: "3"
            - name: KAFKA_RETRY_QUEUE_CAP
              value: "10000"
            - name: OTEL_SERVICE_NAME
              value: "code-manage-service"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317" 
---
apiVersion: v1
kind: Service
metadata:
  name: code-manage-service
  namespace: app-services
spec:
  selector:
    app: code-manage-service
  ports:
  - name: grpc
    protocol: TCP
    port: 50053
    targetPort: 50053
  - name: metrics
    protocol: TCP
    port: 9103
    targetPort: 9103
