apiVersion: apps/v1
kind: Deployment
metadata:
  name: problem-service
  namespace: app-services
spec: 
  replicas: 1
  selector:
    matchLabels:
        app: problem-service
  template:
    metadata:
      labels:
        app: problem-service
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for Redis to be available on port 6379..."
              while ! nc -z -w 1 redis 6379; do
                echo "Redis not yet ready. Sleeping for 5 seconds..."
                sleep 5
              done
              echo "Redis is ready!"
          env:
            - name: REDIS_HOST
              value: "redis"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
      - name: problem-service
        image: akashcapro/codex-problem-service:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
        - containerPort: 9102
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: REDIS_URL
            value: "redis://redis:6379"
          - name: GRPC_PROBLEM_SERVICE_SERVER_URL
            value: "0.0.0.0:50052"
          - name: PROBLEM_SERVICE_METRICS_PORT
            value: "9102"
          - name: PROBLEM_DETAILS_CACHE_EXPIRY
            value: "86400"
          - name: OTEL_SERVICE_NAME
            value: "problem-service"
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"           
        envFrom:
          - secretRef:
              name: app-secrets 
---
apiVersion: v1
kind: Service
metadata:
  name: problem-service
  namespace: app-services
spec:
  selector:
    app: problem-service
  ports:
  - name: grpc
    protocol: TCP
    port: 50052
    targetPort: 50052
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102