alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  additionalScrapeConfigs:
    - job_name: 'otel-collector'
      static_configs:
        - targets: ['otel-collector-opentelemetry-collector.observability.svc.cluster.local:9464']
      metrics_path: /metrics
      scrape_interval: 15s