apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  AUTH_USER_SERVICE_DATABASE_URL: {{ .Values.AUTH_USER_SERVICE_DATABASE_URL | quote }}
  AUTH_USER_SERVICE_DIRECT_URL: {{ .Values.AUTH_USER_SERVICE_DIRECT_URL | quote }}
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.JWT_ACCESS_TOKEN_SECRET | quote }}
  JWT_REFRESH_TOKEN_SECRET: {{ .Values.JWT_REFRESH_TOKEN_SECRET | quote }}
  JWT_INVITE_TOKEN_SECRET: {{ .Values.JWT_INVITE_TOKEN_SECRET | quote }}
  NODEMAILER_PASS: {{ .Values.NODEMAILER_PASS | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.GOOGLE_CLIENT_ID | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.CLOUDINARY_CLOUD_NAME | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.CLOUDINARY_API_SECRET | quote }}
  CLOUDINARY_API_KEY: {{ .Values.CLOUDINARY_API_KEY | quote }}
  PROBLEM_SERVICE_DATABASE_URL: {{ .Values.PROBLEM_SERVICE_DATABASE_URL | quote }}
  COLLAB_SERVICE_DATABASE_URL: {{ .Values.COLLAB_SERVICE_DATABASE_URL | quote }}
  GEMINI_API_KEY: {{ .Values.GEMINI_API_KEY | quote }}
