apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}
  namespace: app-services
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "svc.fullname" . }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
